version: '3'

services:
  client:
    build:
      context: .
      dockerfile: ./Dockerfile
    environment: 
      API_URL: http://my-awesome-api-in-js-docker.com
      NODE_ENV: production
    ports:
    - 80:80
